NUM_DANCERS = 3
IS_EVAL = 1

SERVER_HOST = '127.0.0.1'
SERVER_PORT = 65432        # Port to listen on

SECRET_KEY = b'1234567890abcdef'
EVAL_HOST = '137.132.92.127'
EVAL_PORT = 8889
# EVAL_HOST = '127.0.0.1'
# EVAL_PORT = 8888

PREDICTION_LIST_SIZE = 3
BIGGER_PREDICTION_LIST_SIZE = 5
TOTAL_PREDICTION_LIST_SIZE = 9
PREDICTION_LIST_SIZES = (TOTAL_PREDICTION_LIST_SIZE, BIGGER_PREDICTION_LIST_SIZE, PREDICTION_LIST_SIZE)

PREPROCESSED_VECTOR_LEN = 210
NUM_CLOCK_SYNC_ITERATIONS = 10

DELAY_AFTER_SUBMISSION = 5
DUMMY_SYNCDELAY = 2000

BLUNO_LAPTOP_CONNECTED = 'connected'
BLUNO_LAPTOP_DISCONNECTED = 'disconnected'