import queue

global dataQueue
dataQueue = queue.Queue()

PACKET_WINDOW_SIZE = 40
DANCING_STATE = 1
CONSECUTIVE_IDLE_PACKETS_THRESHOLD = 20
NUM_CONSECUTIVE_PACKETS_THRESHOLD = 10
NUM_ACTIVE_PACKETS_THRESHOLD = 10
NUM_CLOCK_SYNC_ITERATIONS = 10
